// <auto-generated />
using DDSWebstore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace DDSWebstore.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("DDSWebstore.Models.BoughtItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<int>("OrderID");

                    b.Property<float>("Price");

                    b.Property<int>("Quantity");

                    b.HasKey("ID");

                    b.ToTable("BoughtItem");
                });

            modelBuilder.Entity("DDSWebstore.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ItemID");

                    b.Property<string>("Tag");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("DDSWebstore.Models.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImageURL");

                    b.Property<int>("ItemID");

                    b.HasKey("ID");

                    b.HasIndex("ItemID");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("DDSWebstore.Models.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<float>("Price");

                    b.Property<int>("Quantity");

                    b.HasKey("ID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("DDSWebstore.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("city");

                    b.Property<string>("state");

                    b.Property<string>("streetAddress");

                    b.Property<int>("zipcode");

                    b.HasKey("ID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("DDSWebstore.Models.Image", b =>
                {
                    b.HasOne("DDSWebstore.Models.Item", "Item")
                        .WithMany("Images")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
